FROM node:14.16 AS build
WORKDIR /srv/hermes.cam

ARG VERSION="2021.0.0"

COPY . .

RUN yarn
RUN yarn build

FROM node:14.16
WORKDIR /srv/hermes.cam
COPY --from=build /srv/hermes.cam/build .
ENTRYPOINT ["sh", "-c", "serve -s ."]
