FROM nerdscomputing/hermes.cam:from AS build
WORKDIR /srv/hermes.cam

ARG VERSION="2021.0.0"

COPY . .

RUN echo '{ "version": "'$VERSION'" }' > ./public/version.json

RUN yarn
RUN yarn build

FROM node:14.16-alpine
WORKDIR /srv/hermes.cam
COPY --from=build /srv/hermes.cam/build .

RUN npm install -g serve

ENTRYPOINT ["sh", "-c", "serve -s -l 80 ."]
